### ISSUE TITLE
Any way to troubleshoot this not working when the keytab has been verified working

### ISSUE THREAD

**Issue by leonj1** [ubccr/kerby#9]
I have verified the keytab works using these troubleshooting steps:
```
kdestroy
kinit -kt file.keytab USER@REALM
klist
```
But when I pass the keytab and principal, same as above, it fails to authenticate.
The keytab path is the absolute path including the filename.
The principal is exactly the same.
No error message that I can tell.
Both running as root.

Anyway I can troubleshoot?
Is there a debug option?
Any ideas come to mind?
Thanks

**Comment by leonj1** [comment]
The problem here was the KRB5 file environment variable was defined.
And I also had a variable scope problem in my Go code.
Neither are issues with this project, just me being an idiot.

**Comment by aebruno** [comment]
Thanks for reporting back. Glad to hear you got it sorted out.
